import type {ActionSchemas} from '@plunk/shared';
import type {z} from 'zod';

import {DASHBOARD_URI} from '../app/constants.js';
import {prisma} from '../database/prisma.js';
import {NotFound, ValidationError} from '../exceptions/index.js';
import {ContactService} from './ContactService.js';
import {DomainService} from './DomainService.js';
import {EmailService} from './EmailService.js';

/** A `POST /v1/send` request body, as `ActionSchemas.send` parses it. */
export type SendRequest = z.infer<typeof ActionSchemas.send>;

export interface SendRecipient {
  email: string;
  name?: string;
}

/**
 * A send request resolved against its project: the recipients, and the sender and content each of
 * them gets. The subject and body are not rendered yet; the placeholders are filled in per
 * recipient.
 */
export interface PreparedSend {
  projectId: string;
  recipients: SendRecipient[];
  subject: string;
  body: string;
  from: string;
  fromName?: string;
  replyTo?: string;
  templateId?: string;
  data?: Record<string, unknown>;
  subscribed?: boolean;
  headers?: SendRequest['headers'];
  attachments?: SendRequest['attachments'];
}

/** An email created and queued for one recipient, as `POST /v1/send` reports it. */
export interface QueuedEmail {
  contact: {id: string; email: string};
  email: string;
}

/**
 * Transactional sends: what `POST /v1/send` does once its request is authenticated and parsed.
 */
export class TransactionalSendService {
  /**
   * Resolve a send request against its project: normalize the recipients, take the sender and
   * content from the request and its template, and check the sender's domain. Every refusal it
   * raises comes before anything is written.
   *
   * Inline subject/body are templates too, but they are deliberately NOT syntax
   * checked here. Transactional bodies are generated by whatever system calls us —
   * Handlebars output, front-end framework markup, an unbalanced `{{` in a code
   * sample — and those sent fine before Liquid existed. Rejecting them now would
   * break live integrations over markup the renderer already handles by falling back
   * to plain placeholder substitution. Authoring-time surfaces (templates, campaigns)
   * are where a syntax error is worth failing the write.
   */
  public static async prepare(projectId: string, request: SendRequest): Promise<PreparedSend> {
    const {to, subject, body, subscribed, name, from, reply, headers, data, template, attachments} = request;

    // Normalize recipients to array and parse email/name
    const recipients: SendRecipient[] = (Array.isArray(to) ? to : [to]).map(recipient => {
      if (typeof recipient === 'string') {
        return {email: recipient};
      } else {
        return {email: recipient.email, name: recipient.name};
      }
    });

    // Parse 'from' field - can be string or object {name, email}
    let emailFrom: string | undefined;
    let emailFromName: string | undefined;

    if (typeof from === 'string') {
      // Backward compatible: from is just an email string
      emailFrom = from;
      emailFromName = name; // Use separate 'name' field if provided
    } else if (from && typeof from === 'object') {
      // New format: from is an object with {name, email}
      emailFrom = from.email;
      emailFromName = from.name || name; // Prefer from.name, fallback to separate 'name' field
    } else {
      // No 'from' provided
      emailFromName = name;
    }

    // Fetch template if provided
    let emailSubject = subject;
    let emailBody = body;
    let emailReplyTo = reply;
    let templateId: string | undefined;

    if (template) {
      const templateRecord = await prisma.template.findUnique({
        where: {
          id: template,
          projectId, // Ensure template belongs to this project
        },
      });

      if (!templateRecord) {
        throw new NotFound('Template', template);
      }

      // Use template values, allow overrides from request
      emailSubject = subject || templateRecord.subject;
      emailBody = body || templateRecord.body;

      // Handle from field - if not already set and template has a from, use it
      if (!emailFrom && templateRecord.from) {
        emailFrom = templateRecord.from;
      }
      if (!emailFromName && templateRecord.fromName) {
        emailFromName = templateRecord.fromName;
      }

      emailReplyTo = reply || templateRecord.replyTo || undefined;
      templateId = templateRecord.id;
    }

    if (!emailFrom) {
      throw new ValidationError(
        [
          {
            field: 'from',
            message: 'Sender email is required either in request or template',
            code: 'required',
          },
        ],
        'Could not parse sender email',
      );
    }

    await DomainService.verifyEmailDomain(emailFrom, projectId);

    return {
      projectId,
      recipients,
      // The schema requires both unless a template supplies them.
      subject: emailSubject!,
      body: emailBody!,
      from: emailFrom,
      fromName: emailFromName,
      replyTo: emailReplyTo,
      templateId,
      data: data as Record<string, unknown> | undefined,
      subscribed,
      headers,
      attachments,
    };
  }

  /**
   * Send a prepared email to one recipient: create or update the contact, fill in the
   * placeholders, then create and queue the email.
   */
  public static async sendTo(send: PreparedSend, recipient: SendRecipient): Promise<QueuedEmail> {
    // Merge recipient name with data if provided
    const recipientData = recipient.name ? {...send.data, name: recipient.name} : send.data;

    // Create or update contact with metadata
    // Transactional emails should not subscribe contacts by default
    // New contacts default to unsubscribed unless explicitly opted in
    // Existing contacts preserve their subscription state unless explicitly changed
    const contact = await ContactService.upsert(send.projectId, recipient.email, recipientData, send.subscribed, false);

    // Get merged data including non-persistent fields for template rendering
    const mergedData = ContactService.getMergedData(contact, send.data);

    // Add system variables (email, unsubscribe URLs, etc.) to merged data
    // These are always available for template rendering
    const dataWithSystemVars = {
      ...mergedData,
      id: contact.id,
      email: contact.email,
      data: mergedData, // Also available as nested data for {{data.fieldName}} syntax
      unsubscribeUrl: `${DASHBOARD_URI}/unsubscribe/${contact.id}`,
      subscribeUrl: `${DASHBOARD_URI}/subscribe/${contact.id}`,
      manageUrl: `${DASHBOARD_URI}/manage/${contact.id}`,
    };

    const email = await EmailService.sendTransactionalEmail({
      projectId: send.projectId,
      contactId: contact.id,
      subject: this.renderPlaceholders(send.subject, dataWithSystemVars),
      body: this.renderPlaceholders(send.body, dataWithSystemVars),
      from: send.from,
      fromName: send.fromName,
      toName: recipient.name,
      replyTo: send.replyTo,
      headers: send.headers || undefined,
      attachments: send.attachments || undefined,
      templateId: send.templateId,
    });

    return {
      contact: {
        id: contact.id,
        email: contact.email,
      },
      email: email.id,
    };
  }

  /** Send a prepared email to each of its recipients, in order. */
  public static async sendToAll(send: PreparedSend): Promise<QueuedEmail[]> {
    const emails: QueuedEmail[] = [];
    for (const recipient of send.recipients) {
      emails.push(await this.sendTo(send, recipient));
    }
    return emails;
  }

  /**
   * Simple template variable replacement: `{{fieldname}}`, and `{{fieldname ?? fallback}}` for a
   * value that is missing or empty. Placeholders without a value are removed.
   */
  private static renderPlaceholders(text: string, variables: Record<string, unknown>): string {
    let rendered = text;

    for (const [key, value] of Object.entries(variables)) {
      const placeholder = new RegExp(`\\{\\{\\s*${key}\\s*\\}\\}`, 'g');
      const fallbackPlaceholder = new RegExp(`\\{\\{\\s*${key}\\s*\\?\\?\\s*([^}]+)\\}\\}`, 'g');

      // Replace with value
      const stringValue = value !== null && value !== undefined ? String(value) : '';
      rendered = rendered.replace(placeholder, stringValue);

      // Handle fallback syntax: {{field ?? default}}
      rendered = rendered.replace(fallbackPlaceholder, stringValue || '$1');
    }

    // Replace any remaining placeholders with empty string or fallback value
    rendered = rendered.replace(/\{\{\s*(\w+)\s*\}\}/g, '');

    // Handle fallback placeholders that weren't matched
    return rendered.replace(/\{\{\s*\w+\s*\?\?\s*([^}]+)\}\}/g, '$1');
  }
}
