import {EmailSourceType, EmailStatus} from '@plunk/db';
import type {ActionSchemas} from '@plunk/shared';
import type {z} from 'zod';

import {DASHBOARD_URI} from '../app/constants.js';
import {prisma} from '../database/prisma.js';
import {NotFound, ValidationError} from '../exceptions/index.js';
import {uuidv5} from '../utils/uuid.js';
import {ContactService} from './ContactService.js';
import {DomainService} from './DomainService.js';
import {TEMPLATING_HEADER} from './EmailHeaderService.js';
import {EmailService} from './EmailService.js';
import {QueueService} from './QueueService.js';

/** A `POST /v1/send` request body, as `ActionSchemas.send` parses it. */
export type SendRequest = z.infer<typeof ActionSchemas.send>;

export interface SendRecipient {
  email: string;
  name?: string;
}

/**
 * A send request resolved against its project: the recipients, and the sender and content each of
 * them gets. The subject and body are not rendered yet; the placeholders are filled in per
 * recipient.
 */
export interface PreparedSend {
  projectId: string;
  recipients: SendRecipient[];
  subject: string;
  body: string;
  from: string;
  fromName?: string;
  replyTo?: string;
  templateId?: string;
  data?: Record<string, unknown>;
  subscribed?: boolean;
  headers?: SendRequest['headers'];
  attachments?: SendRequest['attachments'];
  /** False: the subject and body are sent as they are, placeholders and all. */
  templating: boolean;
}

/** An email created and queued for one recipient, as `POST /v1/send` reports it. */
export interface QueuedEmail {
  contact: {id: string; email: string};
  email: string;
}

/** The namespace of the email ids derived from an idempotency claim (see `emailIds`). */
const CLAIMED_EMAIL_NAMESPACE = '3d32fa1c-25fe-4376-bf2f-11b83f558336';

function isUniqueViolation(error: unknown): boolean {
  return error instanceof Error && 'code' in error && error.code === 'P2002';
}

/**
 * Transactional sends: what `POST /v1/send` does once its request is authenticated and parsed.
 */
export class TransactionalSendService {
  /** The recipients of a request, in order: `to` as a list of addresses with optional names. */
  public static recipientsOf(to: SendRequest['to']): SendRecipient[] {
    // Normalize recipients to array and parse email/name
    return (Array.isArray(to) ? to : [to]).map(recipient => {
      if (typeof recipient === 'string') {
        return {email: recipient};
      } else {
        return {email: recipient.email, name: recipient.name};
      }
    });
  }

  /**
   * The ids of the emails a request working under an idempotency claim creates, one per recipient.
   * Each derives from the claim, the recipient's address and how often that address came earlier in
   * the request, so a retry of the request arrives at the same emails, however it orders them.
   */
  public static emailIds(claimId: string, recipients: SendRecipient[]): string[] {
    const earlier = new Map<string, number>();
    return recipients.map(({email}) => {
      const address = ContactService.normalizeEmail(email);
      const occurrence = earlier.get(address) ?? 0;
      earlier.set(address, occurrence + 1);
      return uuidv5(`${claimId}:${address}:${occurrence}`, CLAIMED_EMAIL_NAMESPACE);
    });
  }

  /** The emails requests under this claim have created so far for the request's recipients, in its order. */
  public static async findQueued(projectId: string, request: SendRequest, claimId: string): Promise<QueuedEmail[]> {
    const ids = this.emailIds(claimId, this.recipientsOf(request.to));
    const emails = await prisma.email.findMany({
      where: {id: {in: ids}, projectId},
      select: {id: true, contact: {select: {id: true, email: true}}},
    });

    const byId = new Map(emails.map(email => [email.id, email]));
    return ids.flatMap(id => {
      const email = byId.get(id);
      return email ? [{contact: email.contact, email: email.id}] : [];
    });
  }

  /**
   * Resolve a send request against its project: normalize the recipients, take the sender and
   * content from the request and its template, and check the sender's domain. Every refusal it
   * raises comes before anything is written.
   *
   * Inline subject/body are templates too, but they are deliberately NOT syntax
   * checked here. Transactional bodies are generated by whatever system calls us —
   * Handlebars output, front-end framework markup, an unbalanced `{{` in a code
   * sample — and those sent fine before Liquid existed. Rejecting them now would
   * break live integrations over markup the renderer already handles by falling back
   * to plain placeholder substitution. Authoring-time surfaces (templates, campaigns)
   * are where a syntax error is worth failing the write.
   */
  public static async prepare(projectId: string, request: SendRequest): Promise<PreparedSend> {
    const {to, subject, body, subscribed, name, from, reply, headers, data, template, attachments} = request;

    const recipients = this.recipientsOf(to);

    // Parse 'from' field - can be string or object {name, email}
    let emailFrom: string | undefined;
    let emailFromName: string | undefined;

    if (typeof from === 'string') {
      // Backward compatible: from is just an email string
      emailFrom = from;
      emailFromName = name; // Use separate 'name' field if provided
    } else if (from && typeof from === 'object') {
      // New format: from is an object with {name, email}
      emailFrom = from.email;
      emailFromName = from.name || name; // Prefer from.name, fallback to separate 'name' field
    } else {
      // No 'from' provided
      emailFromName = name;
    }

    // Fetch template if provided
    let emailSubject = subject;
    let emailBody = body;
    let emailReplyTo = reply;
    let templateId: string | undefined;

    if (template) {
      const templateRecord = await prisma.template.findUnique({
        where: {
          id: template,
          projectId, // Ensure template belongs to this project
        },
      });

      if (!templateRecord) {
        throw new NotFound('Template', template);
      }

      // Use template values, allow overrides from request
      emailSubject = subject || templateRecord.subject;
      emailBody = body || templateRecord.body;

      // Handle from field - if not already set and template has a from, use it
      if (!emailFrom && templateRecord.from) {
        emailFrom = templateRecord.from;
      }
      if (!emailFromName && templateRecord.fromName) {
        emailFromName = templateRecord.fromName;
      }

      emailReplyTo = reply || templateRecord.replyTo || undefined;
      templateId = templateRecord.id;
    }

    if (!emailFrom) {
      throw new ValidationError(
        [
          {
            field: 'from',
            message: 'Sender email is required either in request or template',
            code: 'required',
          },
        ],
        'Could not parse sender email',
      );
    }

    await DomainService.verifyEmailDomain(emailFrom, projectId);

    return {
      projectId,
      recipients,
      // The schema requires both unless a template supplies them.
      subject: emailSubject!,
      body: emailBody!,
      from: emailFrom,
      fromName: emailFromName,
      replyTo: emailReplyTo,
      templateId,
      data: data as Record<string, unknown> | undefined,
      subscribed,
      headers,
      attachments,
      templating: request.templating !== false,
    };
  }

  /**
   * Send a prepared email to one recipient: create or update the contact, fill in the
   * placeholders, then create and queue the email. Given an `emailId` that an email already has,
   * that email is the recipient's, and nothing is written.
   */
  public static async sendTo(send: PreparedSend, recipient: SendRecipient, emailId?: string): Promise<QueuedEmail> {
    if (emailId) {
      const existing = await this.findClaimedEmail(send.projectId, emailId);
      if (existing) {
        return existing;
      }
    }

    // Merge recipient name with data if provided
    const recipientData = recipient.name ? {...send.data, name: recipient.name} : send.data;

    // Create or update contact with metadata
    // Transactional emails should not subscribe contacts by default
    // New contacts default to unsubscribed unless explicitly opted in
    // Existing contacts preserve their subscription state unless explicitly changed
    const contact = await ContactService.upsert(send.projectId, recipient.email, recipientData, send.subscribed, false);

    // Get merged data including non-persistent fields for template rendering
    const mergedData = ContactService.getMergedData(contact, send.data);

    // Add system variables (email, unsubscribe URLs, etc.) to merged data
    // These are always available for template rendering
    const dataWithSystemVars = {
      ...mergedData,
      id: contact.id,
      email: contact.email,
      data: mergedData, // Also available as nested data for {{data.fieldName}} syntax
      unsubscribeUrl: `${DASHBOARD_URI}/unsubscribe/${contact.id}`,
      subscribeUrl: `${DASHBOARD_URI}/subscribe/${contact.id}`,
      manageUrl: `${DASHBOARD_URI}/manage/${contact.id}`,
    };

    try {
      const email = await EmailService.sendTransactionalEmail({
        id: emailId,
        projectId: send.projectId,
        contactId: contact.id,
        subject: send.templating ? this.renderPlaceholders(send.subject, dataWithSystemVars) : send.subject,
        body: send.templating ? this.renderPlaceholders(send.body, dataWithSystemVars) : send.body,
        from: send.from,
        fromName: send.fromName,
        toName: recipient.name,
        replyTo: send.replyTo,
        // Tells the worker to skip its own rendering too.
        headers: send.templating ? send.headers || undefined : {...send.headers, [TEMPLATING_HEADER]: 'off'},
        attachments: send.attachments || undefined,
        templateId: send.templateId,
      });

      return {
        contact: {
          id: contact.id,
          email: contact.email,
        },
        email: email.id,
      };
    } catch (error) {
      // A concurrent request under the same claim created the email first.
      const existing =
        emailId && isUniqueViolation(error) ? await this.findClaimedEmail(send.projectId, emailId) : null;
      if (existing) {
        return existing;
      }
      throw error;
    }
  }

  /**
   * Send a prepared email to each of its recipients, in order. Under an idempotency claim, each
   * recipient's email gets the id `emailIds` derives, so a retry finds the emails already created.
   */
  public static async sendToAll(send: PreparedSend, claimId?: string): Promise<QueuedEmail[]> {
    const ids = claimId ? this.emailIds(claimId, send.recipients) : [];
    const emails: QueuedEmail[] = [];
    for (const [index, recipient] of send.recipients.entries()) {
      emails.push(await this.sendTo(send, recipient, ids[index]));
    }
    return emails;
  }

  /**
   * An email a request under the same claim already created. It is queued again while it waits to
   * be sent, in case that request died between creating and queueing it; the queue ignores a job it
   * already holds.
   */
  private static async findClaimedEmail(projectId: string, id: string): Promise<QueuedEmail | null> {
    const email = await prisma.email.findFirst({
      where: {id, projectId},
      select: {id: true, status: true, contact: {select: {id: true, email: true}}},
    });

    if (!email) {
      return null;
    }

    if (email.status === EmailStatus.PENDING) {
      await QueueService.queueEmail(email.id, EmailSourceType.TRANSACTIONAL);
    }

    return {contact: email.contact, email: email.id};
  }

  /**
   * Simple template variable replacement: `{{fieldname}}`, and `{{fieldname ?? fallback}}` for a
   * value that is missing or empty. Placeholders without a value are removed.
   */
  private static renderPlaceholders(text: string, variables: Record<string, unknown>): string {
    let rendered = text;

    for (const [key, value] of Object.entries(variables)) {
      // A key is data the caller chose, so it matches literally: `a(b` must not break the pattern.
      const name = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      const placeholder = new RegExp(`\\{\\{\\s*${name}\\s*\\}\\}`, 'g');
      const fallbackPlaceholder = new RegExp(`\\{\\{\\s*${name}\\s*\\?\\?\\s*([^}]+)\\}\\}`, 'g');

      // Replace with value, literally: a `$1` or `$&` in a value is text, not a replacement pattern
      const stringValue = value !== null && value !== undefined ? String(value) : '';
      rendered = rendered.replace(placeholder, () => stringValue);

      // Handle fallback syntax: {{field ?? default}}
      rendered = rendered.replace(fallbackPlaceholder, (_match, fallback: string) => stringValue || fallback);
    }

    // Replace any remaining placeholders with empty string or fallback value
    rendered = rendered.replace(/\{\{\s*(\w+)\s*\}\}/g, '');

    // Handle fallback placeholders that weren't matched
    return rendered.replace(/\{\{\s*\w+\s*\?\?\s*([^}]+)\}\}/g, '$1');
  }
}
